# These are supported funding model platforms

github: [hetrox8] # Replace with up to 4 GitHub Sponsors-enabled usernames
patreon: [SULEIMAN GACHERU]# Replace with a single Patreon username
open_collective: user # Replace with a single Open Collective username
ko_fi: user # Replace with a single Ko-fi username
tidelift: npm/babel # Replace with a single Tidelift platform-name/package-name
community_bridge: project-name # Replace with a single Community Bridge project-name
liberapay: user # Replace with a single Liberapay username
issuehunt: user # Replace with a single IssueHunt username
lfx_crowdfunding: project-name # Replace with a single LFX Crowdfunding project-name
polar: user # Replace with a single Polar username
buy_me_a_coffee: [hetrox8] # Replace with a single Buy Me a Coffee username
custom: ['link1', 'link2'] # Replace with up to 4 custom sponsorship URLs
